### ISSUE TITLE
How to add custom router?

### ISSUE THREAD

**Issue by imagine10255** [deptno/nextjs-typescript-boilerplate#10]
Hi, I use typescript in nextjs 5
but use custom router show typescript error is:
```
Error:(9, 22) TS2306:File '/Users/apple/Documents/project/with-typescript-app/src/routes.ts' is not a module.
```
can you help me ? thx o_o

**Comment by deptno** [comment]
not enough information but,

> In TypeScript, just as in ECMAScript 2015, any file containing a top-level import or export is considered a module. Conversely, a file without any top-level import or export declarations is treated as a script whose contents are available in the global scope (and therefore to modules as well).

[typescript module article](https://www.typescriptlang.org/docs/handbook/modules.html) may help you.

this is not a issue related `next.js-typescript-starter-kit`.
if you need more advice. feel free to email me
