### ISSUE TITLE
Following the install steps will yield 263 vulnerabilites

### ISSUE THREAD

**Issue by nicu-chiciuc** [deptno/nextjs-typescript-boilerplate#18]
After the `npm install` process is finished the output ends with this:
`found 263 vulnerabilities (77 low, 166 moderate, 19 high, 1 critical)
  run 'npm audit fix' to fix them, or 'npm audit' for details`

**Comment by deptno** [comment]
Thank you for the report.

As I checked, 'package-lock.json' seems to be an old version. 'package-lock.json' hasn't been updated since I use 'yarn'.

I delete the 'package-lock.json' and 'npm install', the situation looks much better. I'll commit it.

```
added 1951 packages from 1098 contributors and audited 40458 packages in 30.844s
found 1 low severity vulnerability
```
