### ISSUE TITLE
Styles outside of components error

### ISSUE THREAD

**Issue by ahoyahoy** [deptno/nextjs-typescript-boilerplate#2]
I cannot use 

```
import * as css from 'styled-jsx/css'
const button = css`button { color: hotpink; }`
```

error:

> [ts] Cannot invoke an expression whose type lacks a call signature. Type 'typeof 'styled-jsx/css'' has no compatible call signatures.

**Comment by nikolajlovenhardt** [comment]
Hi @ahoyahoy. A colleague of mine has tried to get in touch with you without luck, and so I'm trying to reach out here (I'm sorry for the inconvenience). Would you please contact Morten Samson ms(at)spotonmarketing.dk.

Thank you in advance (!)

**Comment by deptno** [comment]
```typescript
import css from 'styled-jsx/css'

const button = css`button { color: hotpink; }`

export const Button = props => (
  <button>
    <style jsx>{button}</style>
      i’m button
  </button>
)
```

I adjusted the next.js/5 with typescript and i’ve tested it
