### ISSUE TITLE
_document.tsx: .overrides is not allowed in preset options

### ISSUE THREAD

**Issue by fyn-dev** [deptno/nextjs-typescript-boilerplate#20]
Just clone the project 
`git clone https://github.com/deptno/next.js-typescript-starter-kit.git testnxj`

then
```
cd testnxj
npm install
npm run start:dev
```
After all getting this issue

> Module build failed: Error: [BABEL] .../testnxj/pages/_app.tsx: .overrides is not allowed in preset options
>     at .../testnxj/node_modules/@babel/core/lib/config/validation/options.js:64:13
>     at Array.forEach (<anonymous>)
>     at validate (.../testnxj/node_modules/@babel/core/lib/config/validation/options.js:62:21)
>     at .../testnxj/node_modules/@babel/core/lib/config/full.js:242:36
>     at cachedFunction (.../testnxj/node_modules/@babel/core/lib/config/caching.js:40:17)
>     at loadPresetDescriptor (.../testnxj/node_modules/@babel/core/lib/config/full.js:234:45)
>     at .../testnxj/node_modules/@babel/core/lib/config/full.js:58:19
>     at Array.map (<anonymous>)
>     at recurseDescriptors (.../testnxj/node_modules/@babel/core/lib/config/full.js:56:36)
>     at recurseDescriptors (.../testnxj/node_modules/@babel/core/lib/config/full.js:87:27)
>     at loadFullConfig (.../testnxj/node_modules/@babel/core/lib/config/full.js:103:6)
>     at .../testnxj/node_modules/@babel/core/lib/transform.js:26:33
>     at _combinedTickCallback (internal/process/next_tick.js:132:7)
>     at process._tickCallback (internal/process/next_tick.js:181:9)

**Comment by deptno** [comment]
I'am going to apply next.js@7,
anyway you can run with **yarn** now

before
```bash
rm -rf node_modules package-lock.json
yarn
yarn start:dev
```

**Comment by deptno** [comment]
I updated `README.md` https://github.com/deptno/next.js-typescript-starter-kit/commit/4257ad122fb4762257f14f7f36510a248cf727b6

Thank you!
