### ISSUE TITLE
Serving sitemap.xml

### ISSUE THREAD

**Issue by tomyitav** [deptno/nextjs-typescript-boilerplate#23]
Hi @deptno, thanks for creating this great project!
I wondered if you could share how to serve sitemap.xml file. Or maybe even adding this option to the starter kit. Thanks again!

**Comment by deptno** [comment]
Sorry for delayed response .

`sitemap.xml` is considered almost last step of production frontend deployment. I don't  have `sitemap.xml` knowledge enough now. But I prepare to deploy my project. That time I'll share it.
