### ISSUE TITLE
Cannot found resource file

### ISSUE THREAD

**Issue by AkoWu101** [deptno/nextjs-typescript-boilerplate#24]
These two file get 404 error. Where should i place these files?

<link rel="shortcut icon" href="/static/img/favicon.ico"/>
<link rel="stylesheet" href="/_next/static/style.css" />

**Comment by deptno** [comment]
What two files?

I've checked and I found `isomorphic-fetch` is missing.
I'm add it and pushed.

**Comment by AkoWu101** [comment]
favicon.ico and style.css

**Comment by deptno** [comment]
`favicon.ico` is not supported. think it as sample code
`style.css` is legacy code(before next@7), it's unnecessary. so It should be deleted.
