### ISSUE TITLE
div inside Home.css is having a lint error

### ISSUE THREAD

**Issue by Tanapruk** [deptno/nextjs-typescript-boilerplate#26]
https://github.com/deptno/next.js-typescript-starter-kit/blob/master/src/components/Home.css

```
div {
    background: var(--colorPrimary);
    color: var(--colorSecondary);
}
```

div tag inside Home.css is having lint problem.
What config do I need to make the error go away.

I'm using Visual Studio Code Version 1.31.1 (1.31.1)

Thanks,

**Comment by deptno** [comment]
I don't use lint 🤔, sorry for late answer.
