### ISSUE TITLE
nested styles

### ISSUE THREAD

**Issue by ahoyahoy** [deptno/nextjs-typescript-boilerplate#3]
not working with
```
<style jsx>{`{
      div {
        background: yellow;

        span {
          color: blue;
        }
      }
    }`}</style>
```
> Home.tsx: Nesting detected at 7:9. Unfortunately nesting is not supported by styled-jsx.

I dont know if css plugins are loaded.

Can you enhance styles loading with https://github.com/zeit/next-plugins/tree/master/packages/next-css ?

thx

**Comment by deptno** [comment]
I don’t know styled-jsx supports postCSS,

I applied @zeit/next-css you suggest, however, you can load external css(I thought you originally want to) like this

```
import css from ‘./legacy.css’
```

or

```
import css from ‘./module.css’

export default _ => <div className={css[‘classNameYouDefined’]}>text</div>
```

It works with nested styles(check `postcss.config.js`)
I will prepare example section and documentation

thank you for your feedback
